apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-pwa-dashboard
  labels:
    app.kubernetes.io/name: k8s-pwa-dashboard
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-pwa-dashboard
  labels:
    app.kubernetes.io/name: k8s-pwa-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-pwa-dashboard
subjects:
  - kind: ServiceAccount
    name: k8s-pwa-dashboard
    namespace: k8s-pwa-dashboard
