apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard
  namespace: k8s-dashboard
  labels:
    app.kubernetes.io/name: k8s-dashboard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: k8s-dashboard
  ports:
    - name: http-ui
      port: 80
      targetPort: http-ui
    - name: http-api
      port: 3001
      targetPort: http-api
