version: "1.0"

# Namespace, které se mají vyřadit (blacklist)
excludeNamespaces:
  - kube-system
  - kube-public
  - kube-node-lease
  - default
  - actions-runner-system
  - external-secrets
  - ingress-nginx
  - permission-manager
  - cert-manager
  - adminer

settings:
  pollingInterval: 5000
  scalingEnabled: true
